### ISSUE TITLE
Transferring ownership

### ISSUE THREAD

**Issue by adamjstewart** [conda-forge/typeshed-client-feedstock#6]
@JelleZijlstra would you be interested in maintaining this conda recipe? I clearly haven't had the bandwidth to keep it up to date as it's only a dependency of a dependency for me.

**Comment by JelleZijlstra** [comment]
I don't use Conda and have no idea what goes into maintaining a recipe, so I'm not sure I'd be a good person to maintain this.

**Comment by adamjstewart** [comment]
I don't either, but my users do 😄 

Basically, this is the only file you will ever touch: https://github.com/conda-forge/typeshed-client-feedstock/blob/main/recipe/meta.yaml

It's relatively straightforward and conda has good documentation for what everything means. Whenever a new release appears on PyPI, a bot automatically opens a PR here to update the recipe. The only thing you need to do is make sure the dependencies are still correct.

If you have any other maintainers or community members who would like to maintain this recipe, that is also fine with me.

**Comment by JelleZijlstra** [comment]
Alright, I can take that on.

**Comment by adamjstewart** [comment]
Awesome, I'll open a PR to make this happen.

**Comment by adamjstewart** [comment]
Alright, you are now the proud owner of the conda-forge recipe.

You'll notice that there are a few open PRs to update the current version of the recipe that I (regrettably) ignored. You can either work through them one at a time to package all versions, or simply skip to the latest version. If you read the instructions, there should be a way to automatically regenerate the PR so you don't have to manually rebase.

I'm happy to help with this transition and get you up to date, but just didn't want to maintain this forever. Thanks for your help!
